coreweave/tensorizer

README.md
protobuf.py
tensorizer.py
test_tensorizer.py

I've also implemented a fallback to the `RequestsStreamFile` in case the user is running the tensorizer on a systems that aren't Unix-based since `CURLStreamFile` works with Unix dependencies.

Add Stable Diffusion support and cross-platform serialization

---

tensorizer/_wide_pipes.py
tensorizer/serialization.py
tensorizer/stream_io.py
tensorizer/utils.py
tests/test_serialization.py
tests/test_stream_io.py

This PR contains many bug fixes and compatibility enhancements across the package for the tensorizer rework. Notably, this branch implements full Windows support at this time, and obviates the need for a `RequestsStreamFile` implementation.
Almost all bug fixes are isolated in their own commit for more details:
- 615479038258e2ef770966a64e73b1074aea0f01 Fixes .s3cfg handling
- 064e1f582b8347daba7e7775f48d8b53121d6459 Fixes `begin` offsets in `CURLStreamFile`
- 3b5b35b17b5dd94de40dda1ae0883d29ebd7e5b1 Fixes various bugs when requesting unsupported modes from `stream_io` streams
- 6f0f230e5f9f9944e92e1870a05c84cdf851019b Fixes a case where writing to `s3://` streams could trigger two uploads of the same data, and properly cleans up temporary files
- ad48943bb04bdf4157441b8ee1d77d4b74046b34 …

Many bug fixes and enhancements

---

tensorizer/serialization.py
tests/test_serialization.py

* Add hashing of tensors.
* Some attempted fixes to `mmap`.
* Make tensorizer metadata headers self-consistent after each tensor write.

Tensor Hashing, Self-Consistency, Attempted Fixes to `mmap`.

---

pyproject.toml
tensorizer/stream_io.py
tests/test_serialization.py

To make the default behaviour of `stream_io.open_stream()` more ergonomic for the common use case of specifying an `s3://` URI pointing to a public-read bucket, downloads (but not uploads) now tentatively attempt to proceed with blank credentials if none were specified and no s3cmd config file was found, and include a descriptive error message warning that blank credentials were used only if this leads to the download failing later on.
This approach avoids having to check credentials pre-emptively, prevents warning spam for that use case, and doesn't swallow up errors about invalid config files when they were intended to be used.
Additionally, cURL errors from `CURLStreamFile` now attempt to include cURL's own error text when possible, including HTTP error codes.

Allow unspecified credentials for public-read buckets

---

examples/hf_serialization.py
examples/requirements.txt

`ModelMixin` was moved from the root directory in Diffusers to `models`, this enables the example to work with the latest Diffusers version (0.14.0).

Fix broken Diffusers import in HuggingFace Example

---

pyproject.toml
tensorizer/stream_io.py

A `RuntimeError` is created when a `CURLStreamFile` is instantiated but `curl` is not available, but due to a bug, that error hasn't been raised, just created and then discarded. This leads to an extremely cryptic error a short while later when attempting a streaming load without actually having `curl`.
This fixes the logic involved to actually raise the created error, and bumps `tensorizer` to version `1.1.1`.
In code, this changes:
```py
if curl_path is None:
RuntimeError(
"cURL is a required dependency for streaming downloads"
" and could not be found."
)
```
To:
```py
if curl_path is None:
raise RuntimeError(
"cURL is a required dependency for streaming downloads"
" and could not be found."
)
```

fix(stream_io): Raise an error when `curl` is required, but not found

---

README.md
examples/hf_serialization.py
pyproject.toml
tensorizer/_NumpyTensor.py
tensorizer/serialization.py
tests/test_serialization.py

This PR adds support for models using `torch.bfloat16`.
Tensorizer uses numpy to save the tensors as binary and numpy doesn't support `bfloat16`. This means that special conversions need to be applied which decreases the performance of both serialization and deserialization.
To be saved, the torch tensor is cast to fp32, adding an additional 16 bits. This value is converted to numpy, then bit shifted and cast down to a `np.uint16` to save the original 16 bits from torch's `bfloat16`. The reverse happens during the deserialization process.
Datapoints are averages over 5 runs and use GPT-J-6B cast to the respective precision. All were run on pods with the same CPU/RAM/GPU and were reading/writing the files from a PVC.
| Process         | fp16    | bfloat16 | …

feat: Add support for bfloat16 models

---

tensorizer/stream_io.py
tests/test_serialization.py

This change fixes two bugs:
- Newer versions of boto3/botocore take issue with our method of providing blank (empty string) keys to indicate public buckets.
- This is fixed by switching to use completely unsigned S3 URLs for public buckets.
- Our `tests/test_serialization.check_deserialized()` check has been failing because tensorizer doesn't match PyTorch's behaviour with non-persistent buffers in state dicts.
- Normally, a buffer in a module registered with `module.register_buffer(..., persistent=False)` does not appear in subsequent calls to `module.state_dict()`
- The contents of these are intended to be generated at runtime ([see the original proposal here](https://github.com/pytorch/pytorch/issues/18056))
- `tensorizer` serializes and deserializes these like any other buffers, so …

fix: Support unsigned S3 requests & non-persistent buffers better

---

.pre-commit-config.yaml
examples/benchmark/deserialize_benchmark.py
examples/benchmark/save_models.py
tensorizer/serialization.py
tests/test_serialization.py

This PR contains fixes and updates for #34.
- Fixed `load_into_module` ignoring its `verify_hash` parameter
- Fixed a crash in `load_into_module` when a deserialized submodule is not present in the reference module
- Fixed a leaked `memoryview` on failed hash verification causing errors in `TensorDeserializer.close()` and `TensorDeserializer.__del__()`
- Added `test_verification_fail` to verify `verify_hash` failures outside of `TensorDeserializer.verify_module()`
- Added additional checks to `test_module_verification_fail` to ensure it caught the correct modified submodule
- Switched from `accel-object` to the `object` endpoint when reading from the `s3://tensorized` bucket during test cases
- Switched from `assert` statements to more descriptive `unittest.TestCase.assert*` methods
- …

fix: Hash Verification Fixes & Polish

---

CHANGELOG.md
pyproject.toml
tensorizer/serialization.py

This change adds a `verify_hash` parameter to `TensorDeserializer.read_tensors()` and bumps the code version to v2.1.1.
The nearly-identical function `TensorDeserializer.read_numpy_arrays()` had this parameter added in #34, and `read_tensors()` was intended to mirror that addition, but it was left out.

fix: Add missing `verify_hash` parameter to `read_tensors()`

---

tensorizer/serialization.py
tensorizer/stream_io.py

This adds response headers to the `CURLStreamFile `class by using curl's `--dump-header /dev/stderr` option, and reading from `stderr=subprocess.PIPE`. The bonus is that we can detect when we did not get a `HTTP 1.1 2*` response and handle it accordingly.
Also adds a few more tracking attributes:
* `popen_latencies`: A list of the time it took to start the cURL process.
* `http_response_latencies`: A list of the time it took to get the first HTTP response from the server.
* `response_headers`: A dictionary of the HTTP response headers.
* `bytes_read`: The number of bytes read from the stream.
* `bytes_skipped`: The number of bytes skipped from the stream.
* `read_operations`: The number of read operations performed on the stream.

(feat)Add request header to `CURLStreamFile` along with additional metrics.

---

CHANGELOG.md
tensorizer/_version.py
tensorizer/serialization.py
tests/test_serialization.py

This change increases performance on `TensorSerializer.write_module()` by about 3x, and even more on CUDA modules.
Serializing a CPU module is always (and always has been) faster than serializing a CUDA module, but this change hides several latencies and narrows this speed gap.
When writing many tensors as an atomic operation—e.g. in a call to `write_module`—it is not necessary for an individual entry to be complete (both tensor and header written) before work begins on the next tensor **as long as all tensors and all headers are written before the `write_module` call returns.** This fact opens up more possibilities for optimization when analyzing latencies between **separate tensor writes.**
In fact, several classes of latency slow down the previous implementation more than throughput …

perf(serialization): Optimize bulk serialization through concurrency

---

README.md

For convenience as well as to update the SD examples as per https://github.com/coreweave/kubernetes-cloud/issues/251, the model artifacts that are going to be used in the updated SD examples have been uploaded to the `s3://tensorized` bucket and the README has been updated in this PR to reflect these changes accordingly.

feat: Add image diffusion models to the README

---

tensorizer/_version.py
tensorizer/serialization.py
tests/test_serialization.py

This change groups encoding and decoding logic for header and metadata entries into dedicated classes, completely separate from the `TensorSerializer` and `TensorDeserializer` classes. `TensorSerializer` was already mostly updated to do this in #46, so this mainly affects `TensorDeserializer`.
This disentangles most of the *parsing* of `tensorizer`'s custom binary format from the *use* of that data, making it easier to update and optimize the deserializer's major bottlenecks like I/O, hash computation, and device transfer as was done in the serializer.

refactor: Reorganize Deserialization Parsing

---

tensorizer/stream_io.py

Signed-off-by: Robin H. Johnson <rjohnson@coreweave.com>

feat(stream_io): align presigned URLs to improve HTTP cache hit rates

---

.github/workflows/test.yml
README.md
examples/benchmark_buffer_size/Dockerfile
examples/benchmark_buffer_size/README.md
examples/benchmark_buffer_size/benchmark.py
examples/benchmark_buffer_size/benchmark.yaml
examples/benchmark_buffer_size/redis-server.yaml
examples/requirements.txt
pyproject.toml
requirements.txt
tensorizer/_wide_pipes.py
tensorizer/serialization.py
tensorizer/stream_io.py
tests/requirements.txt
tests/test_serialization.py
tests/test_stream_io.py

This is a preliminary implementation of Redis support by implementing a `RedisStreamFile` class.
```
RedisStreamFile implements a file-like object around a Redis key namespace. Each
'file' is broken up into multiple keys, each of which is a slice of the file. Each
key is named with the prefix, followed by a colon, a user-assigned name, another
colon, and then the byte index of the key.
For example, if the prefix is 'foo', and the user-assigned name is 'bar', then the
keys would be 'foo:bar:0', 'foo:bar:16'. The first key would be the first 16 bytes
of the file, and the remainder would be in the next key.
On initialization, it performs a prefix scan of the keys for the prefix, and then
sorts the keys by their byte index. This allows it to perform a seek operation
efficiently, as it can …
```

(feat)Add preliminary Redis support.

---

examples/benchmark_buffer_size/benchmark.py
examples/benchmark_buffer_size/benchmark.yaml
tensorizer/serialization.py

* Adds `plaid_mode_buffers` argument to `TensorDeserializer` that (currently) defaults to `4`
* Adds JSONL output support to benchmarking, DRY's up logging
* Adds `--start_plaid_buffers`, `--end_plaid_buffers`, `--iterations`, `--test-s3`, `--test-https` arguments to `benchmark.py`.

`plaid_mode_buffers` argument, JSON support, `lazy_load` assumptions

---

CHANGELOG.md
tensorizer/_version.py
tensorizer/stream_io.py
tests/test_stream_io.py

This PR builds off of #59 by @spmkone and closes #58.
- `stream_io.open_stream` and `stream_io.CURLStreamFile` now accept an additional, optional `certificate_handling` argument to customize the verification of SSL certificates
- This corresponds to the flags [`--cacert`](https://curl.se/docs/manpage.html#--cacert), [`--capath`](https://curl.se/docs/manpage.html#--capath), and [`-k`/`--insecure`](https://curl.se/docs/manpage.html#-k) in `curl`
- Customization is achieved by passing an instance of `stream_io.CAInfo` to `open_stream` or the `CURLStreamFile` constructor
- Example usages:
- `open_stream("https://localhost/model.tensors", certificate_handling=CAInfo(cacert="./localhost.pem")`
- `open_stream("https://127.0.0.1/model.tensors", certificate_handling=CAInfo(allow_untrusted=True)`
- …

feat: Expose cURL's `--cacert` and `--capath`, along with `--insecure`

---

tensorizer/stream_io.py
tests/test_stream_io.py

- Useful for HTTPS links with self-signed certificates. 
- #58 
Say, you bringup up a local [minio](https://github.com/minio/minio) S3 endpoint with self-signed certificates (created using [certgen](https://github.com/minio/certgen)).
```bash
podman run -p 9000:9000 -p 9001:9001 -v $HOME/.minio:/root/.minio -v $HOME/work/bucket:/data quay.io/minio/minio server /data --console-address ":9001"
```
You can get a file stream with `stream_io.open_stream` with the `allow_insecure` flag enabled. Which can then be passed onto `TensorDeserializer`.
```python
stream = stream_io.open_stream("s3://model.tensor",
mode="rb",
s3_access_key_id='minioadmin',
s3_secret_access_key='minioadmin',
s3_endpoint='https://127.0.0.1:9000',
allow_insecure=True)
```
Without the `allow_insecure` flag, the call will …

Allow insecure curl downloads with CURLStreamFile

---

tensorizer/serialization.py

This PR replaces the original tensor size calculation for bulk writing which summed the sizes of each tensor's `UntypedStorage` size with an approach that calculates the tensor size based off of the number of elements and the size of each elements.
The issue that the original tensor size calculation prevented was that it did not account for views or shared storages. For example, Megatron has a `main_grad` tensor in each parameter which is a view from a larger buffer where all of the `main_grad` objects share the same storage object. With the previous method on a 6B model, the original size calculation returns ~6GiB for each `main_grad` tensor despite the actual tensor being a fraction of the size. In the end, it attempted to write 1.3TiB of data for all of the `main_grad` tensors.
The new …

fix: Correct tensor size calculation in TensorSerializer

---

pyproject.toml
tensorizer/serialization.py
tensorizer/stream_io.py
tests/test_serialization.py

Tensor encryption and decryption.
Some design decisions and notes:
- We only encrypt the actual tensor payload itself. This helps us avoid a format change. There's a case to encrypting the metadata header as well, but that requires a format change so I'm punting that.
- We leverage the existing hash fields to contain the salt, nonce, and block_size for each tensor.
- Encryption is easy. Just provide passphrase= argument to the Deserializer and Serializer.
- We follow good practices, such as: random nonce's, ensuring that there's a new nonce each and every time, salting the passphrase with a random salt.
- By design, we don't encrypt the entire tensor payload in one go -- instead we use a streaming block cipher, xsalsa20 with poly HMAC -- this allows us to decrypt concurrently with reads …

feat(crypto): Initial pass at crypto implementation.

---

examples/hf_serialization.py

Miscellaneous fixes and improvements for #73.
- Fixes calling `serialize_model` with a default `model_prefix`
- Fixes indentation for saved config files
- Fixes checking local files for emptiness
- Doesn't use `lazy_load=True` when it's not helpful
- Uses a more accurate timing function
- Refactors S3 stream credential propagation

fix(examples): Miscellaneous `hf_serialization.py` fixes

---

CHANGELOG.md
tensorizer/serialization.py
tests/test_serialization.py

This change fixes serialization for large tensors (roughly over 2147479552 bytes in a single tensor) by using multiple calls to `write` or `pwrite` when not everything is written during the first call.
This also enhances support for serializing to an unbuffered Python file-like object, since those can have similar behaviour.

fix(serialization): Support serializing tensors over `write` size limits

---

tensorizer/_syscalls.py
tensorizer/serialization.py
tests/test_syscalls.py

This change switches the `posix_fallocate` pre-allocation step during serialization to instead use the [Linux `fallocate(2)` syscall](https://linux.die.net/man/2/fallocate), skipping pre-allocation if it is not supported (e.g. if the call raises `EOPNOTSUPP`).
Previously, calling `posix_fallocate` on filesystems that do not support native `fallocate` behaviour would result in extremely poor performance from manually writing zeroes to a file. Since pre-allocation only exists as a performance optimization anyway, it's better to skip it when it is not available.

perf(serialization): Use Linux `fallocate` instead of `posix_fallocate`

---

examples/hf_serialization.py
examples/requirements.txt

This fix enforces `s3_endpoint = "object.ord1.coreweave.com"` for writes as well as reads in `hf_serialization.py` rather than `"accel-object.ord1.coreweave.com"` to prevent unwanted caching of model tensors. Caching tensors isn't helpful for a workflow with the sole purpose of serializing and validating model tensors, as this would just prevent overwritten tensors from being used for validation, instead using the older, cached ones. Additionally, updated `transformers` and `accelerate` dependencies to allow running `Mistral-7B`.

fix(examples): Ensure using non-cached endpoint when validating

---

tensorizer/_linear_partition.py
tensorizer/serialization.py

This improves the algorithm used to assign segments of a file to reader threads in #87.
An $O(n^{2} \cdot k)$ time, $O(n \cdot k)$ space (where $n$ = number of tensors, $k$ = requested number of readers) dynamic programming algorithm for optimal linear partitioning is used when $\frac{n \cdot (n + 1)}{2} \cdot k \lt 250000$, (less than 250000 comparison operations, about 250 tensors with 8 readers, takes about 140 ms).
When the number of comparison operations to compute the optimal partitioning scheme would be too large, it reverts to [an efficient greedy algorithm originally designed by Sean Werkema](https://www.werkema.com/2021/11/01/an-efficient-solution-to-linear-partitioning/) that takes $O(n)$ time and $O(k)$ space.

perf(serialization): Use optimal linear partitioning to divide segments

---

examples/deserialize.py

During deserialization using `load_into_module`, only the buffers loaded from the deserializer are overwritten on the target module, and any extra buffers on the target module remain unmodified. This can lead to an error if there are existing buffers on the target module that are on a different device from the deserializer, since the model will end up scattered across multiple devices.
This primarily arises as an issue when serializing with `include_non_persistent_buffers=False`, since non-persistent buffers may be created on any device, and will not be overwritten by the deserializer. In particular, this led to an error when running the code in `deserialize.py` (which does not expect buffers from anything but the deserializer) on a model serialized using `examples/hf_serialization.py` …

fix(examples): Move non-persistent buffers to a valid device

---

pyproject.toml
requirements.txt

Customer has a hard requirement for `redis==4.5.5` due to bugs in `5.0.0` for their use case. This relaxes the requirement to `redis>=4.5.5` from `redis==5.0.0`.
Test cases pass for Redis with `4.5.5`.

fix(redis): relax Redis requirements to `>=4.5.5` from `==5.0.0`.

---

tensorizer/serialization.py

Similar to plaid mode, re-use one pinned buffer to handle the data transfer from GPU to CPU for serialization.
In main, serializing gpt-j-6B fp16 to nvme took 8.375s
In this branch, takes 4.796s

perf(serialization) Reuse a pinned buffer when copying from gpu

---

tensorizer/serialization.py

`TensorDeserializer.read_numpy_arrays()` returned unstable results when a `TensorDeserializer`'s `device` parameter was set to a CUDA device. `numpy` arrays cannot be deserialized to CUDA, since `numpy` is a CPU-only library, but the returned CPU buffers still used `plaid_mode` CUDA-oriented semantics, and thus were corrupted shortly after being returned. (This also affects `TensorDeserializer.read_tensors()`, but that will be resolved soon by #87, which will enable that function to properly yield CUDA tensors.)
This PR resolves this issue by raising an error when calling `TensorDeserializer.read_numpy_arrays()` but not deserializing to the CPU, as attempting to do so is contradictory anyway.

fix(serialization): Limit `read_numpy_arrays` to CPU deserialization

---

tensorizer/stream_io.py

This change updates some of the code added in #93 to:
1. Use keyword arguments for `s3_region_name` and `s3_signature_version` in `stream_io.open_stream` instead of reordering the existing parameter list, which would be a breaking change, and
2. Use the `s3_region_name` and `s3_signature_version` parameters on object storage writes as well, as they were only applied to object storage reads.

fix(stream_io): Use region & signature version on S3 writes; use kwargs

---

README.md
tensorizer/_linear_partition.py
tensorizer/_wide_pipes.py
tensorizer/serialization.py
tensorizer/stream_io.py
tests/test_serialization.py
tests/test_stream_io.py

This PR contains various fixes and performance tweaks for #87.
Highlights:
- Open files and `CURLStreamFile`s can be used with `num_readers > 1`
- The linear partitioning algorithm has greatly improved performance and correctness
- Around 25x faster in a common configuration
- `num_tensors=-1` following other partial reads works correctly
- Buffer pointers and artificial references to their sources are avoided in favour of `memoryview`s that directly hold strong references to their sources, lowering the likelihood of memory getting garbage collected while still in use
- Some cryptic error causing S3 reads with `num_readers > 1` to fail has been resolved
- Multiple separate reads share a thread pool
- HTTP `Range` end offsets are requested and handled correctly
- HTTP `Range`s have more …

fix: Avoid regressions, add tests, better reference handling, misc. logic errors

---

tensorizer/serialization.py

When reopening `CURLStreamFile`s for multiple readers, this change makes the reopening logic prefer an existing `CURLStreamFile`'s `._fork` method rather than `open_stream`. `open_stream` is slow to call many times because it must re-compute the pre-signed URL each time, and the way we do that with `boto3` adds a decent amount of overhead.

perf(serialization): Prefer `CURLStreamFile._fork` over `open_stream`

---

tensorizer/stream_io.py

This change fixes a parsing bug that didn't correctly account for object storage endpoint domains prefixed by a bucket name subdomain. It also fixes an off-by-one error when gathering the list of components to check.

fix(stream_io): Fix `accel-object` parsing with bucket name subdomains

---

tensorizer/_syscalls.py

This change adds a `tensorizer_syscalls.prefault` function that can fault pages in memory for writing without holding the GIL, allowing prefaulting to be multithreaded. This accelerates `cudaHostRegister` performance, since it then does not need to fault pages itself.
The `prefault` function uses `madvise` if `MADV_POPULATE_WRITE` is available (Linux 5.14+), or `memset` otherwise, which incurs unnecessary writes, but is still fairly fast. Its arguments must be page-aligned for compatibility with the `madvise` syscall.
No usages of this function are added in the PR—only the function itself, to aid in development of better allocation schemes in subsequent PRs.
Example usage:
```py
import ctypes
import mmap
from concurrent.futures import ThreadPoolExecutor
from tensorizer._syscalls import …
```

perf: Add a syscall-based GIL-free address prefaulting function

---

examples/deserialize.py
pyproject.toml
requirements.txt
tensorizer/serialization.py

This change switches from using the `atomics` package for synchronized variable access to explicit locking, to avoid errors thrown by that package's deallocation code, and also for performance (amusingly). Additionally, the internal-only `_perf_stats` gathered during deserialization are now optional, and are only collected if the environment variable `TENSORIZER_ENABLE_PERF_STATS` is set.

fix(serialization): Drop `atomics` dependency & make perf stats optional

---

.pre-commit-config.yaml
examples/benchmark_buffer_size/visualizations/visualizations.py
pyproject.toml
tensorizer/serialization.py
tensorizer/stream_io.py
tensorizer/utils.py
tests/test_serialization.py

This change updates the pre-commit formatting hooks to use the latest versions of `black` and `isort`.

chore: Update pre-commit hooks

---

tensorizer/_tensor_path.py
tensorizer/serialization.py
tests/test_serialization.py

This change adds serialization for structured objects in a way mirroring JSON.
`TensorSerializer.write_state_dict()` can now serialize nested dictionaries (or other mappings), nested lists (or other sequences), and arbitrary mixtures of dictionaries and lists. Nested structure is accessed at deserialization time either through repeated key lookup or the dedicated `TensorDeserializer.tree` method (open to other names).
The usage is illustrated in the documentation for `TensorDeserializer.tree`:
```py
serializer = TensorSerializer(path)
nested_structure = {
"model": {
"layer": [
{"weight": torch.tensor(...)},
{"weight": torch.tensor(...)},
],
},
"lm_head": torch.tensor(...),
}
serializer.write_state_dict(nested_structure)
serializer.close()
deserializer = TensorDeserializer(path)
assert …
```

feat(serialization): Add serialization of structured objects

---

CHANGELOG.md
examples/deserialize.py
tensorizer/serialization.py

This switches the default number of concurrent readers during deserialization from 1 to a dynamic value based on the file being  deserialized, and the system resources.
The logic to choose how many readers to use by default is:
- Anything that the code doesn't know how to reopen uses 1, otherwise,
- Local files use 8, otherwise,
- Anything using hash verification uses 4, otherwise,
- Anything else uses 2
- If a `CURLStreamFile`'s headers do not include `Accept-Ranges: bytes`, use 1
- Use fewer readers if the number picked is expected to overflow RAM
- E.g. if only the top 4 largest tensors are expected to fit in memory at one time, don't default to more than 4 readers
- This check is still bypassed if a specific `num_readers` is used
- Never use more readers than there are tensors in the …

feat(serialization): Use a dynamic `num_readers` by default

---

CHANGELOG.md
tensorizer/serialization.py
tensorizer/stream_io.py
tests/test_stream_io.py

This change switches the `end` parameter for `CURLStreamFile`s and `open_stream` to mean one-past-the-end, since that matches Python slicing, and is what most Python programmers would expect.
Evidence for this is that our implementation of `CURLStreamFile.read()` and multi-reader deserialization were incorrect because even we all assumed the `end` parameter meant one-past-the-end while developing tensorizer until a bug arose with it during v2.9.0 development. The fix then was to make it match HTTP range behaviour of `end` being inclusive, but that is enough of an unintuitive footgun that it will very likely lead to more bugs later on.
It was also arguably a breaking change, as code already using `CURLStreamFile`s' `end` parameter had their behaviour change.
This PR also fixes bugs with …

fix(stream_io): Use exclusive end for `CURLStreamFile`s + misc bugs

---

README-subprocess-serialization.md
README.md
docs/subprocess-serialization.md

Write up a discussion of how to do serialization in a subprocess, with a few different examples.

[docs] Add documentation about how to do serialization in a separate process

---

tensorizer/_NumpyTensor.py
tensorizer/_futuregroup.py
tensorizer/serialization.py
tests/test_serialization.py

(note this PR is just for merging into the `v3.0.0-dev` branch, not main)
The file schema has changed. Immediately following the metadata block is the full block of all header structures.  
After the metadata and headers is the block of raw tensor data. The block of tensor data begins on a 4k page-aligned boundary (relative to start of file). Each individual tensor begins on an 8-byte-aligned boundary.
Basically:
```
file_header
metadata_size
metadata0
...
metadataN
header0
...
headerN
tensor0 (file_offset % 4096 == 0)
tensor1 (file_offset % 8 == 0)
...
tensorN (file_offset % 8 == 0)
```
We may want to combine the metadata and the header entries, but they are left separate for now for easier backwards compatibility.
Previously, header hash computations included the hash fields themselves, …

[3.0-dev] Major refactor of serialization in prep for 3.0

---

tensorizer/serialization.py
tests/test_serialization.py

This PR complements #163 by adding new tests and tracking per-tensor encryption statuses during serialization to avoid attempting to decrypt tensors that aren't encrypted. Decrypting tensors that are not encrypted normally raises an exception in `tensorizer._crypt` from a MAC mismatch, which makes it fairly safe, but adds noise by spamming concerning-looking decryption errors after an initial error.
If decryption fails during error handling in a bulk write operation, its `CryptographyError` is elevated to be the top-level exception, with the previous top-level exception chained to it. Other non-`CryptographyError` exceptions from the last-ditch decryption step are ignored, since they are likely duplicates of the exception that brought the code to that error path to begin with, and the …

fix(serialization): Track tensor encryption status per-tensor

---

tensorizer/serialization.py
tests/test_serialization.py

Closes #144 
I think this was in better shape than initially expected, because `_maybe_decrypt_data()` did its work in a `finally:` block. Anyway, added two test cases. One that covers the event of a pwrite() raising an exception, and the other of an exception occurring in the main write block before `_maybe_decrypt_data()` is executed. The latter test was failing, and changes to the exception handler have been made to pass.

Ensure that data is decrypted in the event of an exception

---

CHANGELOG.md
tensorizer/stream_io.py

This change repeats a fix from commit 412d0d7c154f55567d2411d9a5704c831cce050b to let `RedisStreamFile` objects be identified as readable by a `TensorDeserializer`. They were broken since they were changed to inherit from `io.BufferedIOBase` in commit b83dec7e83f4e31e8026072bf1e5763b5c6ca62b, which added dysfunctional default implementations for `readable()` and `seekable()` methods.

fix(stream_io): Correctly implement `readable()`/`seekable()` again

---

tests/test_stream_io.py

This change fixes a unit test that was incorrectly failing. It was essentially verifying that the string `X-Amz-Expires` was present in a URL querystring, but that `Expires` wasn't, but didn't properly account for `Expires` being a substring of `X-Amz-Expires`.
It was slightly more nuanced than this, so it didn't fail 100% of the time. This changes the regex so that the search for the substring `Expires` does not match if it is preceded by the substring `X-Amz-`.
This only fixes a unit test and does not require any updated release or changelog notes.

tests(stream_io): Disambiguate `Expires` from `X-Amz-Expires` in regex

---

README.md
tensorizer/_NumpyTensor.py

This change updates the info in the README and internal lookup tables in the code to account for new dtypes introduced in PyTorch between v2.0 and v2.7.
In particular, this documents that `float8_*` and almost all other dtypes are currently supported—everything except for quantized int dtypes.
On the code side, the new dtypes were supported by a fallback mechanism before, but listing them explicitly allows them to be handled faster via table lookups. Because of that, this doesn't change what is supported, but is instead a small performance enhancement.

docs: Update dtype info
